version: '3.5'

services:
  db:
    image: mysql:5.6
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -h 127.0.0.1 ping -P 3306 -ppassword | grep 'mysqld is alive' || exit 1"]
      interval: 5s
      timeout: 30s
      retries: 4

  app:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./nodejs:/app
    tty: true
    ports:
      - "3000"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
      - app